Ext.define("core.rbac.user.view.DeptForm",{
	extend:"Ext.form.Panel",
	alias:"widget.rbac.deptform",
	layout:"auto",
	align:"left",
	frame:true,
	title:"小区信息",
	defaults:{
			selectOnFocus:true,
			msgTarget:"side", //提示信息现在的位置
			width:380
	},
	items:[{
				xtype:"textfield",
				fieldLabel:"主键",
				name:"deptId",
				hidden:true
			},{
				xtype:"textfield",
				fieldLabel:"小区名称",
				name:"deptName"
			},{
				xtype:"textfield",
				fieldLabel:"小区编码",
				name:"deptCode"
			},{
				xtype:"numberfield",
				fieldLabel:"排序",
				name:"orderIndex"
			},{
				xtype:"textfield",
				fieldLabel:"父节点",
				name:"parentId",
				hidden:true
			},{
				xtype:"button",
				ref:"submit",
				text:"保存",
				width:80
			}]
});