Ext.define("core.bl.inc.view.InteractPanel",{
	extend:"core.app.base.BasePanel",
	alias:"widget.bl.interactPanel",
	funCode:"interact_main",
	funData:{
	        action:"/bl/inc", //请求Action
	        whereSql:"",//表格查询条件
	        orderSql:"operatingTime",//表格排序条件
	        pkName:"hId",
	        modelName:"org.yingqu.baoli.model.Interact",//实体全路径
	        tableName:"Interact",//表名
	        defaultObj:{enabled:"1"},//默认信息，用于表格添加的时候字段默认值
	        isChildren:false,//是否子功能
	        children:[{//子功能的配置
	        	funCode:"interactitem_main"	        	
			},
			{//子功能的配置
	        	funCode:"officialPhotograph_main"	        	
			}
			]
	},
		items:[{
		xtype:"basecenterpanel",
				items:[{
					xtype:"basequerypanel",
					region:"north",
					items:[
			  {
				xtype:"basequeryfield",
				queryType:"textfield",
				fieldLabel:"用户名",
				name:"username",
				config:{
				}
			},
			  {
				xtype:"basequeryfield",
				queryType:"basecombobox",
				fieldLabel:"分类",
				name:"type",
				config:{
					ddCode:"INCATYPE"
				}
			},
			  {
				xtype:"basequeryfield",
				queryType:"textfield",
				fieldLabel:"标题",
				name:"title",
				config:{
				}
			},
			  {
				xtype:"basequeryfield",
				queryType:"datetimefield",
				fieldLabel:"发布时间",
				name:"ptime",
				config:{
					dateType : 'datetime'
				}
			},
			]
			},{
			xtype:"bl.interactGrid",
			region:"center"
		}]
	},{
	xtype:"bl.interactForm",
		hidden:true
	}]
});
